import {describe,it,expect} from 'vitest';
import {applyDeduction,candidates,conflicts,countSolutions,deduction,digits,fresh,logicalGrade,peers,put,units,validateSnapshot} from './logic';
import {decodeSave} from './storage';
import bank from './puzzles.json';
import legacy from '../scripts/legacy-puzzles.json';
describe('curated deterministic bank',()=>{
 it('contains 120 distinct puzzles with forty per actual logical grade',()=>{expect(bank).toHaveLength(120);expect(new Set(bank.map(p=>p.grid.join(''))).size).toBe(120);for(const level of ['easy','medium','hard'])expect(bank.filter(p=>p.difficulty===level)).toHaveLength(40)});
 it('preserves every legacy ID, grid and grade exactly',()=>{for(const p of legacy)expect(bank.find(n=>n.id===p.id)).toEqual(p)});
 it('has distinct clue layouts, including geometric symmetries',()=>{const normalize=(g:number[])=>{const masks:string[]=[];for(let flip=0;flip<2;flip++)for(let rotate=0;rotate<4;rotate++){const mask=Array(81).fill(0);for(let i=0;i<81;i++){let r=Math.floor(i/9),c=i%9;if(flip)c=8-c;for(let n=0;n<rotate;n++)[r,c]=[c,8-r];mask[r*9+c]=g[i]?1:0;}masks.push(mask.join(''));}return masks.sort()[0]};expect(new Set(bank.map(p=>normalize(p.grid))).size).toBe(bank.length)});
 for(const p of bank){it(`${p.id}: unique, correctly graded, all coach premises sound to completion`,()=>{expect(countSolutions(p.grid)).toBe(1);expect(logicalGrade(p.grid)).toEqual(p.grade);expect(p.grade.remaining).toBe(0);let s=fresh(p.grid),steps=0;while(s.grid.some(d=>!d)){const h=deduction(s.grid,s.excluded);expect(h).not.toBeNull();if(!h)break;const cs=candidates(s.grid,s.excluded);expect(h.explanation.length).toBeGreaterThan(25);expect(h.premises.length).toBeGreaterThan(0);if(h.kind==='naked')expect(cs[h.target]).toEqual([h.digit]);if(h.kind==='hidden')expect(h.unit.filter(i=>cs[i].includes(h.digit))).toEqual([h.target]);if(h.eliminate){expect(h.kind).toBe('locked');expect(h.premises.length).toBeGreaterThanOrEqual(2);const box=units.slice(18).find(u=>h.premises.every(i=>u.includes(i)));expect(box).toBeDefined();expect(box!.filter(i=>cs[i].includes(h.digit))).toEqual(h.premises);const row=Math.floor(h.premises[0]/9),col=h.premises[0]%9;expect(h.premises.every(i=>Math.floor(i/9)===row)||h.premises.every(i=>i%9===col)).toBe(true);expect(h.eliminate.every(i=>!box!.includes(i))).toBe(true);for(const cell of h.eliminate){expect(cs[cell]).toContain(h.digit);const invalid=[...s.grid];invalid[cell]=h.digit;expect(countSolutions(invalid,1)).toBe(0)}}else{for(const digit of digits.filter(d=>d!==h.digit)){const invalid=[...s.grid];invalid[h.target]=digit;expect(countSolutions(invalid,1)).toBe(0)}}s=applyDeduction(s,h);expect(conflicts(s.grid)).toEqual([]);expect(++steps).toBeLessThan(100);}expect(steps).toBe(p.grade.steps);expect(countSolutions(s.grid)).toBe(1);for(const u of units)expect(u.map(i=>s.grid[i]).sort()).toEqual(digits);});}
});
describe('logic boundaries',()=>{
 it('detects ambiguity without assuming a stored solution',()=>{expect(countSolutions(Array(81).fill(0))).toBe(2);expect(deduction(Array(81).fill(0))).toBeNull()});
 it('candidates exactly eliminate row column and box digits',()=>{const g=Array(81).fill(0);g[1]=1;g[9]=2;g[10]=3;g[80]=4;expect(candidates(g)[0]).toEqual([4,5,6,7,8,9]);expect(peers[0]).toHaveLength(20)});
 it('detects duplicate cells and no solution',()=>{const g=Array(81).fill(0);g[0]=g[8]=5;expect(conflicts(g)).toEqual([0,8]);expect(countSolutions(g)).toBe(0)});
 it('rejects invalid solver input',()=>{expect(countSolutions([1])).toBe(0);expect(countSolutions(Array(81).fill(10))).toBe(0)});
 it('givens remain immutable and pencil toggle preserves grid',()=>{const p=bank[0],s=fresh(p.grid),given=p.grid.findIndex(Boolean),empty=p.grid.indexOf(0);expect(put(s,p.grid,given,0)).toBe(s);const t=put(s,p.grid,empty,4,true);expect(t.notes[empty]).toEqual([4]);expect(t.grid[empty]).toBe(0);expect(put(t,p.grid,empty,4,true).notes[empty]).toEqual([]);expect(s.notes[empty]).toEqual([])});
 it('value edits clear derived exclusions',()=>{const p=bank[0],s=fresh(p.grid),i=p.grid.indexOf(0);s.excluded[i]=[1];const next=put(s,p.grid,i,2);expect(next.excluded.flat()).toEqual([]);expect(next.grid[i]).toBe(2)});
 it('rejects malformed public input coordinates and digits without changing the board',()=>{const p=bank[0],s=fresh(p.grid),i=p.grid.indexOf(0);for(const digit of [NaN,Infinity,.5,-1,10])expect(put(s,p.grid,i,digit)).toBe(s);for(const cell of [NaN,Infinity,.5,-1,81])expect(put(s,p.grid,cell,1)).toBe(s)});
 it('hidden singles derived from confirmed exclusions explain and highlight that basis',()=>{let s=fresh(bank.find(p=>p.id==='p118')!.grid);let found=false;for(let n=0;n<100;n++){const h=deduction(s.grid,s.excluded);if(!h)break;if(h.kind==='hidden'){const eliminated=h.unit.filter(i=>!s.grid[i]&&s.excluded[i].includes(h.digit));if(eliminated.length){found=true;expect(h.explanation).toContain('之前已确认的候选排除');for(const i of eliminated)expect(h.premises).toContain(i)}}s=applyDeduction(s,h)}expect(found).toBe(true)});
 it('locked deduction preserves manual notes',()=>{let s=fresh(bank.find(p=>p.difficulty==='hard')!.grid);for(let i=0;i<100;i++){const d=deduction(s.grid,s.excluded)!;if(d.eliminate){s.notes[0]=[7,8];const n=applyDeduction(s,d);expect(n.notes).toEqual(s.notes);expect(n.excluded[d.target]).toContain(d.digit);return;}s=applyDeduction(s,d)}throw new Error('no lock found')});
});
describe('versioned safe persistence',()=>{
 const p=bank[0];const valid={version:1,puzzleId:p.id,snapshot:fresh(p.grid),seconds:22};
 it('round-trips and discards persisted logical exclusions',()=>{const save=structuredClone(valid);save.snapshot.excluded[0]=[5];expect(decodeSave(JSON.stringify(save))?.snapshot.excluded.flat()).toEqual([])});
 it.each(['','null','{','[]',JSON.stringify({...valid,version:2}),JSON.stringify({...valid,puzzleId:'missing'}),JSON.stringify({...valid,seconds:-1})])('rejects corrupt / unknown save %s',raw=>expect(decodeSave(raw)).toBeNull());
 it('rejects overwritten givens',()=>{const save=structuredClone(valid);save.snapshot.grid[p.grid.findIndex(Boolean)]=0;expect(decodeSave(JSON.stringify(save))).toBeNull()});
 it('rejects malformed candidate arrays',()=>{const s=fresh(p.grid);s.notes[0]=[1,1];expect(validateSnapshot(s,p.grid)).toBe(false)});
 it('rejects fractional time and malformed assisted flags',()=>{for(const seconds of [.5,'22',true,1e8+1])expect(decodeSave(JSON.stringify({...valid,seconds}))).toBeNull();for(const assisted of ['true',1,{}])expect(decodeSave(JSON.stringify({...valid,assisted}))).toBeNull()});
 it('restores only known fields while preserving manual notes and integer time',()=>{const snapshot=fresh(p.grid),i=p.grid.indexOf(0);snapshot.notes[i]=[1,3];const decoded=decodeSave(JSON.stringify({...valid,unknown:'ignored',snapshot:{...snapshot,unknown:'ignored'}}))!;expect(Object.keys(decoded).sort()).toEqual(['version','puzzleId','snapshot','seconds','assisted','started'].sort());expect(Object.keys(decoded.snapshot).sort()).toEqual(['grid','notes','excluded'].sort());expect(decoded.snapshot.notes[i]).toEqual([1,3]);expect(decoded.seconds).toBe(22)});
 it.each(['grid','notes','excluded'] as const)('infers a started legacy zero-second clock from %s',field=>{const snapshot=fresh(p.grid),i=p.grid.indexOf(0);if(field==='grid')snapshot.grid[i]=1;else snapshot[field][i]=[1];expect(decodeSave(JSON.stringify({...valid,seconds:0,snapshot}))?.started).toBe(true)});
 it('preserves explicit clock state and rejects malformed clock flags',()=>{const save={...valid,seconds:0};expect(decodeSave(JSON.stringify(save))?.started).toBe(false);expect(decodeSave(JSON.stringify({...save,started:true}))?.started).toBe(true);for(const started of ['true',1,{}])expect(decodeSave(JSON.stringify({...save,started}))).toBeNull()});
});
