import {useEffect,useId,useMemo,useRef,useState,type KeyboardEvent as ReactKey} from 'react';
import {applyDeduction,candidates,conflicts,countSolutions,deduction,digits,fresh,peers,pos,put,type Difficulty,type Snapshot} from './logic';
import {readProgress,readSave,writeProgress,writeSave} from './storage';
import {emptyProgress,filterPuzzles,markSolved,markStarted,pickRandomPuzzle,type PuzzleStatus} from './progress';
import bank from './puzzles.json';
import './sudoku.css';
import {createAudio,type GameAudio} from './audio';
export type SudokuGameProps={onExit?:()=>void;onComplete?:(result:{puzzleId:string;seconds:number;assisted:boolean})=>void;persist?:boolean;className?:string;globalKeyboard?:boolean};
type Puzzle=(typeof bank)[number];
const labels={easy:'入门',medium:'进阶',hard:'挑战'};
const formatTime=(n:number)=>`${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toString().padStart(2,'0')}`;
export function SudokuGame({onExit,onComplete,persist=true,className='',globalKeyboard=false}:SudokuGameProps){
 const uniqueId=useId();const audio=useRef<GameAudio|null>(null);
 useEffect(()=>{const a=createAudio('sudoku');audio.current=a;return()=>{a.dispose();audio.current=null}},[]);
 const initial=useMemo(()=>persist?readSave():null,[]);
 const [puzzle,setPuzzle]=useState(()=>bank.find(p=>p.id===initial?.puzzleId)??bank.find(p=>p.difficulty==='easy')!);
 const [history,setHistory]=useState<Snapshot[]>(()=>[initial?.snapshot??fresh(puzzle.grid)]);const [cursor,setCursor]=useState(0);const state=history[cursor];
 const [started,setStarted]=useState(initial?.started??false);
 const [selected,setSelected]=useState<number|null>(null),[pencil,setPencil]=useState(false),[coach,setCoach]=useState(true),[showCandidates,setShowCandidates]=useState(false),[paused,setPaused]=useState(false),[hidden,setHidden]=useState(false),[seconds,setSeconds]=useState(initial?.seconds??0),[assisted,setAssisted]=useState(initial?.assisted??false),[modal,setModal]=useState<'new'|'replace'|'help'|null>(null),[level,setLevel]=useState<Difficulty>(puzzle.difficulty as Difficulty),[notice,setNotice]=useState(initial?'已恢复上次的练习。':''),[storageOK,setStorageOK]=useState(true);
 // Coach hints unfold in three steps: direction (highlighted unit) → target cell → full reasoning.
 const [reveal,setReveal]=useState<{key:string;level:number}>({key:'',level:0});
 const [progress,setProgress]=useState(()=>markStarted(persist?readProgress(initial):emptyProgress(),puzzle.id));
 const [progressStorageOK,setProgressStorageOK]=useState(true),[status,setStatus]=useState<PuzzleStatus>('all'),[chosenId,setChosenId]=useState(puzzle.id),[pendingPuzzle,setPendingPuzzle]=useState<Puzzle|null>(null);
 const root=useRef<HTMLElement>(null),dialog=useRef<HTMLDivElement>(null),lastFocus=useRef<HTMLElement|null>(null),completion=useRef(false);const cells=useRef<(HTMLButtonElement|null)[]>([]);
 const bad=useMemo(()=>conflicts(state.grid),[state.grid]);const complete=state.grid.every(Boolean)&&!bad.length;const filled=state.grid.filter(Boolean).length-puzzle.clues;const total=81-puzzle.clues;
 const cs=useMemo(()=>candidates(state.grid,state.excluded),[state]);
 const possible=useMemo(()=>coach&&!bad.length?countSolutions(state.grid,1)>0:true,[state.grid,coach,bad.length]);
 const hint=useMemo(()=>coach&&!bad.length&&possible?deduction(state.grid,state.excluded):null,[state,coach,bad.length,possible]);
 const hintKey=hint?`${cursor}:${hint.kind}:${hint.target}:${hint.digit}`:'';const hintLevel=reveal.key===hintKey?reveal.level:0;
 const hintDirection=hint?.kind==='naked'?'有一格的同行、同列、同宫已经排除了八个数字。':hint?.kind==='hidden'?'高亮区域里，有一个数字只剩一个能放的位置。':'高亮区域里，某个数字被锁在一条线上，可以排除别处的候选。';
 const levelPuzzles=useMemo(()=>bank.filter(p=>p.difficulty===level),[level]);
 const visiblePuzzles=useMemo(()=>filterPuzzles(bank,level,status,progress),[level,status,progress]);
 const chosenPuzzle=visiblePuzzles.find(p=>p.id===chosenId)??null;
 const completedCount=Object.keys(progress.solved).length;
 const currentLevelPuzzles=bank.filter(p=>p.difficulty===puzzle.difficulty);
 const currentIndex=currentLevelPuzzles.findIndex(p=>p.id===puzzle.id)+1;
 const hasProgress=!complete&&(seconds>0||state.grid.some((d,i)=>d!==puzzle.grid[i])||state.notes.some(n=>n.length)||state.excluded.some(n=>n.length));
 const blocked=paused||hidden||!!modal;const highlighted=selected===null?[]:peers[selected];const selectedValue=selected===null?0:state.grid[selected];
 function commit(next:Snapshot){if(next===state||JSON.stringify(next)===JSON.stringify(state))return;setStarted(true);setHistory(h=>[...h.slice(0,cursor+1),next].slice(-201));setCursor(Math.min(cursor+1,200));setNotice('');}
 function input(d:number){if(blocked||complete)return;if(selected===null){setNotice('先选一个空格，再填数字。');return;}if(puzzle.grid[selected]){setNotice('这是题目给定的数字，不能修改。');return;}if((!pencil||!d||state.grid[selected])&&state.grid[selected]===d&&!state.notes[selected].length)return;const next=put(state,puzzle.grid,selected,d,pencil);audio.current?.play(conflicts(next.grid).length?'error':'tap');commit(next);}
 function keyboard(e:KeyboardEvent|ReactKey){const t=e.target as HTMLElement;if(blocked||t.tagName==='INPUT'||t.tagName==='SELECT'||t.tagName==='TEXTAREA'||t.isContentEditable||e.altKey||e.repeat&&!e.key.startsWith('Arrow'))return;const owned=root.current?.contains(t);if(!owned&&!globalKeyboard)return;
 if(!e.ctrlKey&&!e.metaKey&&/^[1-9]$/.test(e.key)){e.preventDefault();input(Number(e.key));}else if(!e.ctrlKey&&!e.metaKey&&(e.key==='Backspace'||e.key==='Delete'||e.key==='0')){e.preventDefault();input(0);}else if(e.key.toLowerCase()==='n'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();setPencil(p=>!p);}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?setCursor(c=>Math.min(history.length-1,c+1)):setCursor(c=>Math.max(0,c-1));}else if(!e.ctrlKey&&!e.metaKey&&e.key.startsWith('Arrow')&&selected!==null){e.preventDefault();const row=Math.floor(selected/9),col=selected%9;const next=e.key==='ArrowLeft'?row*9+Math.max(0,col-1):e.key==='ArrowRight'?row*9+Math.min(8,col+1):e.key==='ArrowUp'?Math.max(0,row-1)*9+col:Math.min(8,row+1)*9+col;setSelected(next);cells.current[next]?.focus();}}
 useEffect(()=>{if(!globalKeyboard)return;const handler=(e:KeyboardEvent)=>keyboard(e);window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);});
 useEffect(()=>{const vis=()=>setHidden(document.hidden);document.addEventListener('visibilitychange',vis);vis();return()=>document.removeEventListener('visibilitychange',vis)},[]);
 // Persist the first entry independently of elapsed seconds and undo history.
 useEffect(()=>{if(blocked||complete||!started)return;const timer=setInterval(()=>setSeconds(n=>n+1),1000);return()=>clearInterval(timer)},[blocked,complete,started]);
 useEffect(()=>{if(persist)setStorageOK(writeSave({version:1,puzzleId:puzzle.id,snapshot:state,seconds,assisted,started}));},[persist,puzzle.id,state,seconds,assisted,started]);
 useEffect(()=>{if(persist)setProgressStorageOK(writeProgress(progress));},[persist,progress]);
 useEffect(()=>{if(complete&&!completion.current){completion.current=true;setProgress(p=>markSolved(p,puzzle.id,{seconds:Math.floor(seconds),assisted}));audio.current?.play('win');onComplete?.({puzzleId:puzzle.id,seconds,assisted});}},[complete]);
 useEffect(()=>{if(modal==='new'&&!visiblePuzzles.some(p=>p.id===chosenId))setChosenId(visiblePuzzles.find(p=>p.id!==puzzle.id)?.id??visiblePuzzles[0]?.id??'');},[modal,visiblePuzzles,chosenId,puzzle.id]);
 useEffect(()=>{if(!modal)return;lastFocus.current=document.activeElement as HTMLElement;return()=>{lastFocus.current?.focus();}},[!!modal]);
 useEffect(()=>{if(!modal)return;const el=dialog.current;el?.querySelector<HTMLElement>('button:not(:disabled),select')?.focus();const trap=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setModal(modal==='replace'?'new':null);return;}if(e.key!=='Tab'||!el)return;const all=Array.from(el.querySelectorAll<HTMLElement>('button:not(:disabled),select,input,a[href]'));const first=all[0],last=all[all.length-1];if(!first)return;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};el?.addEventListener('keydown',trap);return()=>{el?.removeEventListener('keydown',trap);}},[modal]);
 function openLibrary(){setLevel(puzzle.difficulty as Difficulty);setStatus('all');setChosenId(puzzle.id);setModal('new');}
 function newPuzzle(next:Puzzle){completion.current=false;setPuzzle(next);setProgress(p=>markStarted(p,next.id));setHistory([fresh(next.grid)]);setCursor(0);setSeconds(0);setStarted(false);setSelected(null);setPaused(false);setPencil(false);setAssisted(false);setModal(null);setPendingPuzzle(null);setNotice(`已打开 ${labels[next.difficulty as Difficulty]} ${next.id.toUpperCase()}。慢慢来。`);}
 function requestPuzzle(next:Puzzle|null){if(!next||next.id===puzzle.id)return;if(hasProgress){setPendingPuzzle(next);setModal('replace');}else newPuzzle(next);}
 function randomPuzzle(){requestPuzzle(pickRandomPuzzle(visiblePuzzles,puzzle.id,progress));}

 function apply(){if(!hint||blocked)return;commit(applyDeduction(state,hint));setSelected(hint.target);setAssisted(true);audio.current?.play('success');setNotice(hint.eliminate?'已排除候选，并显示剩余候选。':'已应用这一步推理。');if(hint.eliminate)setShowCandidates(true);}
 return <section ref={root} className={`sg ${className}`} onKeyDown={globalKeyboard?undefined:keyboard} aria-label="九间数独练习室">
 <div className="sg-shell" inert={modal?true:undefined}><header className="sg-header"><div className="sg-brand"><span className="sg-mark" aria-hidden="true">井</span><span>九间<span className="sg-brand-en">NINE ROOMS</span></span></div><div className="sg-header-actions">{onExit&&<button type="button" className="sg-text-button" onClick={onExit}>退出</button>}<button type="button" className="sg-text-button" onClick={()=>setModal('help')}>怎么玩 <span aria-hidden="true">↗</span></button></div></header>
 <div className="sg-intro"><div><p className="sg-eyebrow">A LITTLE ORDER. A LITTLE CALM.</p><h1>给思绪，留一格。</h1><p className="sg-subtitle">不必急着找到答案。看清下一步，就很好。</p></div><span className="sg-edition">逻辑练习室<span>VOL. 01 / 数独</span></span></div>
 <div className="sg-layout"><main className="sg-play"><div className="sg-gamebar"><div className="sg-level"><span className="sg-dot"/>{labels[puzzle.difficulty as Difficulty]} <span className="sg-puzzle-id">/ {puzzle.id.toUpperCase()}</span><span className="sg-puzzle-position">{currentIndex} / {currentLevelPuzzles.length}</span></div><div className="sg-time"><span aria-label="已用时间">{formatTime(seconds)}</span><button type="button" aria-label={paused?'继续游戏':'暂停游戏'} onClick={()=>setPaused(p=>!p)} disabled={complete}>{paused?'▶':'Ⅱ'}</button></div></div>
 <div className="sg-board-wrap"><div className="sg-board" role="group" aria-label="数独棋盘，方向键移动，数字键填写，N 切换笔记" aria-hidden={paused||hidden||undefined}>{state.grid.map((v,i)=><button type="button" key={i} ref={el=>{cells.current[i]=el}} data-cell={i} tabIndex={selected===i||selected===null&&i===0?0:-1} disabled={paused||hidden} aria-label={`${pos(i)}，${v?`${v}${puzzle.grid[i]?'，题目给定':''}`:`空白${state.notes[i].length?`，笔记 ${state.notes[i].join('、')}`:''}`}${bad.includes(i)?'，数字冲突':''}`} aria-pressed={selected===i} onClick={()=>setSelected(i)} className={['sg-cell',puzzle.grid[i]?'sg-given':'sg-entered',selected===i?'sg-selected':'',highlighted.includes(i)?'sg-peer':'',selectedValue&&v===selectedValue?'sg-same':'',bad.includes(i)?'sg-conflict':'',hintLevel>0&&hint?.target===i?'sg-hint-target':'',hintLevel>0&&hint?.premises.includes(i)?'sg-premise':'',hint?.unit.includes(i)?'sg-hint-unit':'',i%9===2||i%9===5?'sg-box-right':'',Math.floor(i/9)===2||Math.floor(i/9)===5?'sg-box-bottom':''].join(' ')}>{v||<span className="sg-notes">{digits.map(d=><span key={d}>{(showCandidates?cs[i]:state.notes[i]).includes(d)?d:''}</span>)}</span>}</button>)}</div>{(paused||hidden)&&<div className="sg-pause"><span>让思绪休息一下</span><p>计时已暂停，棋盘暂时收起。</p><button type="button" onClick={()=>setPaused(false)}>继续练习</button></div>}</div>
 <div className="sg-progress"><span><b>{filled}</b> / {total} 格已完成</span><span>每一步，都有理由。</span></div><div className="sg-progress-line"><span style={{width:`${filled/total*100}%`}}/></div>
 <div className="sg-tools"><button type="button" disabled={blocked||cursor===0} onClick={()=>setCursor(c=>c-1)}><span>↶</span>撤销</button><button type="button" disabled={blocked||cursor===history.length-1} onClick={()=>setCursor(c=>c+1)}><span>↷</span>重做</button><button type="button" disabled={blocked} onClick={()=>input(0)}><span>⌫</span>擦除</button><button type="button" disabled={blocked} aria-pressed={pencil} className={pencil?'sg-active':''} onClick={()=>setPencil(p=>!p)}><span>✎</span>笔记 <small>{pencil?'开':'关'}</small></button></div>
 <div className="sg-keypad" aria-label="数字输入">{digits.map(d=><button type="button" key={d} disabled={blocked||complete} onClick={()=>input(d)} aria-label={`填入 ${d}`}><span>{d}</span><small>{Math.max(0,9-state.grid.filter(v=>v===d).length)}</small></button>)}</div><p className="sg-key-help">{pencil?'笔记模式 · 再点同一数字即可移除':'点击空格，再选择数字'}<span>键盘 1–9 · N 笔记 · ⌫ 擦除</span></p>
 </main><aside className="sg-sidebar"><section className="sg-coach"><div className="sg-card-heading"><span className="sg-mini-icon" aria-hidden="true">✦</span><h2>陪你想一步</h2><button type="button" className="sg-switch" role="switch" aria-checked={coach} aria-label="实时教练" onClick={()=>setCoach(v=>!v)}><span/></button></div><p className="sg-coach-caption">看见推理，而不只是答案。</p>
 {complete?<div className="sg-coach-body"><span className="sg-tag">完成了！</span><h3>九间，归位。</h3><p>用时 {formatTime(seconds)}。{assisted?'你和教练一起，走完了这段推理。':'这一局的每一步，都由你完成。'}</p><button type="button" className="sg-primary" onClick={openLibrary}>再来一局 ↗</button></div>:!coach?<div className="sg-coach-body"><h3>留给你独立思考。</h3><p>随时打开教练，查看当前棋盘上能严格推导的一步。</p></div>:bad.length?<div className="sg-coach-body"><span className="sg-tag sg-error-tag">先检查冲突</span><h3>有数字重复了。</h3><p>红色格子里，相同数字出现在同一行、列或宫。先修改这些格子，教练再继续推理。</p></div>:!possible?<div className="sg-coach-body"><span className="sg-tag sg-error-tag">当前填法不成立</span><h3>没有重复，也可能走偏。</h3><p>当前已填数字无法组成完整解。请撤销或检查最近输入；这不表示哪一格已经被证明正确。</p></div>:hint&&hintLevel===0?<div className="sg-coach-body"><span className="sg-tag">{hint.kind==='locked'?'03':hint.kind==='hidden'?'02':'01'} / {hint.title}</span><h3>先看方向。</h3><p>{hintDirection}浅色高亮的就是线索所在，先自己找找看。</p><button type="button" className="sg-reveal" disabled={blocked} onClick={()=>setReveal({key:hintKey,level:1})}>再提示一点：标出目标格</button><p className="sg-no-spoiler">提示分三步给出，答案留到最后。</p></div>:hint&&hintLevel===1?<div className="sg-coach-body"><span className="sg-tag">{hint.kind==='locked'?'03':hint.kind==='hidden'?'02':'01'} / {hint.title}</span><h3>{pos(hint.target)}</h3><p>目标格和推理依据已在棋盘上标出。{hint.eliminate?'想想哪些候选可以排除。':'想想它只能是几。'}</p><div className="sg-legend"><span><i className="sg-legend-target"/>目标格</span><span><i className="sg-legend-premise"/>推理依据</span></div><button type="button" className="sg-reveal" disabled={blocked} onClick={()=>setReveal({key:hintKey,level:2})}>看完整推理</button></div>:hint?<div className="sg-coach-body"><span className="sg-tag">{hint.kind==='locked'?'03':hint.kind==='hidden'?'02':'01'} / {hint.title}</span><h3>{hint.eliminate?'先排除，再靠近。':`${pos(hint.target)}`}</h3><p>{hint.explanation}</p><div className="sg-legend"><span><i className="sg-legend-target"/>目标格</span><span><i className="sg-legend-premise"/>推理依据</span></div><button type="button" className="sg-primary" disabled={blocked} onClick={apply}>{hint.eliminate?`排除候选 ${hint.digit}`:`应用这一步 · 填入 ${hint.digit}`} <span>↗</span></button><p className="sg-no-spoiler">只有点击应用，教练才会改动棋盘。</p></div>:<div className="sg-coach-body"><span className="sg-tag">留一点探索空间</span><h3>这一步，需要更进阶的技巧。</h3><p>当前没有找到唯一候选、单元唯一位置或宫内锁定。教练不会把预存答案当作推理；你可以继续分析候选数。</p></div>}
 </section><section className="sg-settings"><div className="sg-setting-row"><label htmlFor={`${uniqueId}-candidates`}>显示合法候选<span>按当前数字与已确认排除计算</span></label><input id={`${uniqueId}-candidates`} type="checkbox" checked={showCandidates} onChange={e=>setShowCandidates(e.target.checked)}/></div><AudioControls audio={audio} paused={blocked||complete}/></section>
 <button type="button" className="sg-new" onClick={openLibrary}>题库 · 开启新一局 <span>＋</span></button><p className="sg-library-summary">已完成 <b>{completedCount}</b> / {bank.length} 道 · {progress.solved[puzzle.id]?'这道题已通关':'这道题未完成'}</p><p className="sg-save-note">{persist?(storageOK&&progressStorageOK?'进度与完成记录自动保存 · 离线也能继续':'浏览器阻止了保存，请勿关闭本页'):'嵌入模式 · 本机存档已关闭'}</p><div className="sg-footer-note"><span>「</span>每行、每列、每个九宫格，<br/>让 1 到 9 各出现一次。<span>」</span></div></aside></div>
 <div className="sg-notice" aria-live="polite" role="status">{notice}</div><footer className="sg-footer">九间 · 一次一格，一点秩序。<span>{bank.length} 道独立唯一解题目 / 无需联网</span></footer></div>
 {modal&&<div className="sg-modal-backdrop"><div ref={dialog} className={`sg-modal ${modal==='new'?'sg-library-modal':''}`} role="dialog" aria-modal="true" aria-labelledby={`${uniqueId}-modal-title`}>{modal==='new'?<><p className="sg-eyebrow">ONE PUZZLE AT A TIME</p><h2 id={`${uniqueId}-modal-title`}>下一格，由你选择。</h2><p>共 {bank.length} 道题，已完成 {completedCount} 道。选一道慢慢想，或交给随机。</p>
 <div className="sg-library-filters"><label className="sg-select-label">练习难度<select value={level} onChange={e=>setLevel(e.target.value as Difficulty)}><option value="easy">入门 · 唯一候选数</option><option value="medium">进阶 · 单元唯一位置</option><option value="hard">挑战 · 宫内锁定候选</option></select></label><label className="sg-select-label">完成状态<select value={status} onChange={e=>setStatus(e.target.value as PuzzleStatus)}><option value="all">全部题目</option><option value="unsolved">未完成</option><option value="solved">已完成</option><option value="unplayed">未玩过</option></select></label></div>
 <div className="sg-library-count" aria-live="polite"><span>{labels[level]} · {levelPuzzles.length} 道 / 已完成 {levelPuzzles.filter(p=>progress.solved[p.id]).length} 道</span><span>显示 {visiblePuzzles.length} 道</span></div>
 <div className="sg-puzzle-list" role="group" aria-label="选择题目">{visiblePuzzles.map(p=>{const index=levelPuzzles.findIndex(x=>x.id===p.id)+1;const current=p.id===puzzle.id;const done=!!progress.solved[p.id];const played=progress.started.includes(p.id);return <button type="button" key={p.id} className={`sg-puzzle-tile ${chosenId===p.id?'sg-puzzle-chosen':''} ${done?'sg-puzzle-solved':''}`} aria-pressed={chosenId===p.id} aria-label={`${labels[level]}第 ${index} 题 ${p.id.toUpperCase()}，${current?'当前题目，':''}${done?'已完成':played?'未完成':'未玩过'}`} onClick={()=>setChosenId(p.id)}><b>{String(index).padStart(2,'0')}</b><small>{current?'当前':done?'✓ 已完成':played?'未完成':'未玩过'}</small></button>})}</div>
 {!visiblePuzzles.length&&<p className="sg-library-empty">这里暂时没有题目，换一个筛选条件试试。</p>}
 <p className="sg-selection-note" aria-live="polite">{chosenPuzzle?`${labels[level]}第 ${levelPuzzles.findIndex(p=>p.id===chosenPuzzle.id)+1} / ${levelPuzzles.length} 题 · ${chosenPuzzle.id.toUpperCase()}${progress.solved[chosenPuzzle.id]?` · 上次完成 ${formatTime(progress.solved[chosenPuzzle.id].seconds)}`:''}`:'请选择其他难度或完成状态。'}</p>
 <p className="sg-modal-note">随机优先选未玩过的题，不重复当前题。题目均为唯一解，可用教练支持的技巧完成。切换后只保留完成记录，未完成棋盘会被替换。</p>
 <div className="sg-library-actions"><button type="button" onClick={()=>setModal(null)}>保留当前</button><button type="button" disabled={!visiblePuzzles.some(p=>p.id!==puzzle.id)} onClick={randomPuzzle}>随机一题 ↗</button><button type="button" className="sg-primary" disabled={!chosenPuzzle||chosenPuzzle.id===puzzle.id} onClick={()=>requestPuzzle(chosenPuzzle)}>{chosenPuzzle?.id===puzzle.id?'正在练习':'开始这道题'}</button></div></>:modal==='replace'?<><p className="sg-eyebrow">KEEP YOUR PLACE?</p><h2 id={`${uniqueId}-modal-title`}>要换一张题目吗？</h2><p>当前 {puzzle.id.toUpperCase()} 的数字、笔记和 {formatTime(seconds)} 用时会被替换。已完成题目的记录会保留。</p><p className="sg-confirm-target">即将打开：{pendingPuzzle?`${labels[pendingPuzzle.difficulty as Difficulty]} · ${pendingPuzzle.id.toUpperCase()}`:''}</p><div className="sg-modal-actions"><button type="button" onClick={()=>setModal('new')}>返回题库</button><button type="button" className="sg-primary" onClick={()=>{if(pendingPuzzle)newPuzzle(pendingPuzzle)}}>确认换题</button></div></>:<><p className="sg-eyebrow">SMALL RULES, DEEP THOUGHT</p><h2 id={`${uniqueId}-modal-title`}>让每个数字，恰到好处。</h2><p>每行、每列和每个粗线九宫格，都要填入不重复的 1–9。深色数字是题目给定，绿色数字由你填写。</p><ul><li>选中格子，用数字键或下方按钮填写。</li><li>「笔记」记录你自己的候选；「显示合法候选」显示按规则算出的候选，两者互不覆盖。</li><li>教练高亮目标与依据，只在你点击后应用推理。橙色小点是依据，绿色内框是目标。</li><li>红色表示直接重复；教练也能发现整体无解，但不会拿答案替你判定某格。</li><li>方向键移动，N 切换笔记，⌫ 擦除，Ctrl/⌘ Z 撤销，Ctrl/⌘ Shift Z 重做。后台自动暂停。</li><li>题库可按难度、完成状态选题。随机优先选择未玩过的题，完成记录会单独保存。</li></ul><button type="button" className="sg-primary" onClick={()=>setModal(null)}>明白了，开始思考</button></>}</div></div>}
 </section>;
}
function AudioControls({audio,paused}:{audio:React.RefObject<GameAudio|null>;paused:boolean}){
 const pausedRef=useRef(paused),mounted=useRef(true);pausedRef.current=paused;useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 const [music,setMusic]=useState(false),[sfx,setSfx]=useState(false),[musicVolume,setMusicVolume]=useState(.28),[sfxVolume,setSfxVolume]=useState(.35),[unavailable,setUnavailable]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{if(paused)audio.current?.pause();else void audio.current?.resume()},[paused]);
 async function toggle(which:'music'|'sfx'){if(busy)return;const next=which==='music'?!music:!sfx;setBusy(true);try{if(next&&!await audio.current?.start()){if(mounted.current)setUnavailable(true);return;}if(!mounted.current)return;setUnavailable(false);if(which==='music'){audio.current?.setMusicEnabled(next);setMusic(next);}else{audio.current?.setSfxEnabled(next);setSfx(next);if(next)audio.current?.play('tap');}if(pausedRef.current)audio.current?.pause();}finally{if(mounted.current)setBusy(false)}}
 return <><div className="sg-audio-row"><button type="button" disabled={busy} aria-pressed={music} onClick={()=>void toggle('music')}>背景音乐 <span>{music?'已开':'已关'}</span></button><input aria-label="音乐音量" type="range" min="0" max="1" step="0.01" value={musicVolume} onChange={e=>{const v=Number(e.target.value);setMusicVolume(v);audio.current?.setMusicVolume(v)}}/></div><div className="sg-audio-row"><button type="button" disabled={busy} aria-pressed={sfx} onClick={()=>void toggle('sfx')}>操作音效 <span>{sfx?'已开':'已关'}</span></button><input aria-label="音效音量" type="range" min="0" max="1" step="0.01" value={sfxVolume} onChange={e=>{const v=Number(e.target.value);setSfxVolume(v);audio.current?.setSfxVolume(v)}}/></div><p className="sg-audio-note" role="status">{unavailable?'当前浏览器无法开启声音。':'原创轻音乐 · 默认静音，开启后才播放'}</p></>
}
export default SudokuGame;
