// @vitest-environment jsdom
import React from 'react';
import { cleanup,fireEvent,render,screen,within,act as reactAct } from '@testing-library/react';
import { afterEach,beforeEach,describe,it,expect,vi } from 'vitest';
import { StudGame } from './StudGame';
beforeEach(()=>{localStorage.clear();Object.defineProperty(document,'hidden',{configurable:true,value:false});vi.useFakeTimers()});afterEach(()=>{cleanup();vi.useRealTimers()});
describe('interaction lifecycle',()=>{
 it('keeps scoped keyboard focus on the table when its start button disappears',()=>{const result=render(<StudGame persist={false}/>);const start=screen.getByRole('button',{name:/入席/});start.focus();fireEvent.click(start);expect(screen.queryByRole('button',{name:/入席/})).toBeNull();expect(document.activeElement).toBe(result.container.querySelector('.stud-game'))});
 it('defaults audio off, trap focus, closes Escape and restores focus',()=>{render(<StudGame persist={false}/>);const button=screen.getByRole('button',{name:'设置'});button.focus();fireEvent.click(button);expect((screen.getByRole('checkbox',{name:'原创背景音乐'})as HTMLInputElement).checked).toBe(false);expect((screen.getByRole('checkbox',{name:'牌桌音效'})as HTMLInputElement).checked).toBe(false);const close=screen.getByRole('button',{name:'关闭弹窗'});close.focus();fireEvent.keyDown(close,{key:'Tab',shiftKey:true});expect(document.activeElement).toBe(screen.getByRole('slider',{name:'音效音量'}));fireEvent.keyDown(document,{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();expect(document.activeElement).toBe(button)});
 it('ignores duplicate start and cancels AI/deal timers while paused',()=>{render(<StudGame persist={false}/>);const start=screen.getByRole('button',{name:/入席/});fireEvent.click(start);fireEvent.click(start);expect(screen.getByText(/双人对局/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'暂停'}));const before=screen.getByLabelText('五张梭哈牌桌').textContent;reactAct(()=>vi.advanceTimersByTime(20000));expect(screen.getByLabelText('五张梭哈牌桌').textContent).toBe(before);expect(screen.getByRole('button',{name:/确认下注|有效全下/}).hasAttribute('disabled')).toBe(true)});
 it('new match requires confirmation; stale AI timer cannot play into reset',()=>{render(<StudGame persist={false}/>);fireEvent.click(screen.getByRole('button',{name:/入席/}));fireEvent.click(screen.getByRole('button',{name:/新对局/}));expect(screen.getByRole('dialog')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'确认新对局'}));reactAct(()=>vi.advanceTimersByTime(20000));expect(screen.getByRole('button',{name:/入席/})).toBeTruthy();expect(screen.getAllByText('500')).toHaveLength(2)});
 it('restores valid settled bankroll and ignores corrupt saves',()=>{localStorage.setItem('velvet-stud-v1',JSON.stringify({v:1,stacks:[650,350],hand:4}));const a=render(<StudGame/>);expect(screen.getByText('650')).toBeTruthy();a.unmount();localStorage.setItem('velvet-stud-v1',JSON.stringify({v:1,stacks:[900,900],hand:4}));render(<StudGame/>);expect(screen.getAllByText('500')).toHaveLength(2)});
 it('cleans timers on unmount and supports isolated instances',()=>{const a=render(<><StudGame persist={false}/><StudGame persist={false}/></>);expect(screen.getAllByRole('button',{name:/入席/})).toHaveLength(2);fireEvent.click(screen.getAllByRole('button',{name:/入席/})[0]);a.unmount();reactAct(()=>vi.advanceTimersByTime(20000));expect(vi.getTimerCount()).toBe(0)})
});

import {initial,startHand,act,advance,limits,analyzeDecision,view, type Game} from './engine';
import {SAVE_KEY,saveGame} from './save';
function humanGame(){let g=startHand(initial(),()=>.4);if(g.turn===1)g=act(g,1,{type:'check'});return g}
function resume(g:Game){saveGame(g);render(<StudGame/>);fireEvent.click(screen.getByRole('button',{name:/继续对局/}))}
function stored(){return JSON.parse(localStorage.getItem(SAVE_KEY)!).game as Game}
describe('revision safeguards',()=>{
 it('restores exact cards and pot paused, with no double ante or automatic action',()=>{const g=humanGame();saveGame(g);render(<StudGame/>);expect(screen.getByText('Ⅱ 已恢复牌局 · 待继续')).toBeTruthy();reactAct(()=>vi.advanceTimersByTime(10000));expect(stored()).toEqual(g);fireEvent.click(screen.getByRole('button',{name:/继续对局/}));expect(stored().cards).toEqual(g.cards);expect(stored().pot).toBe(10)});
 it('all-in asks first; Escape and backdrop cancel without spending and restore focus',()=>{resume(humanGame());fireEvent.click(screen.getByRole('button',{name:'封顶'}));const raise=screen.getByRole('button',{name:/有效全下至/});raise.focus();fireEvent.click(raise);const before=stored();reactAct(()=>vi.advanceTimersByTime(5000));expect(stored()).toEqual(before);fireEvent.keyDown(document,{key:'c'});expect(stored()).toEqual(before);fireEvent.keyDown(document,{key:'Escape'});expect(document.activeElement).toBe(raise);expect(stored()).toEqual(before);fireEvent.click(raise);fireEvent.mouseDown(screen.getByRole('dialog').parentElement!);expect(screen.queryByRole('dialog')).toBeNull();expect(stored()).toEqual(before)});
 it('confirmation charges exactly once under rapid repeated clicks',()=>{resume(humanGame());fireEvent.click(screen.getByRole('button',{name:'封顶'}));fireEvent.click(screen.getByRole('button',{name:/有效全下至/}));const confirm=screen.getByRole('button',{name:'确认有效全下'});fireEvent.click(confirm);fireEvent.click(confirm);expect(stored().stacks[0]).toBe(0);expect(stored().pot).toBe(505);expect(stored().logs.filter(s=>s==='你 · 下注至 495')).toHaveLength(1)});
 it('resume accepts scoped shortcuts immediately and all-in confirmation restores a usable focus target',()=>{
  const g=humanGame();resume(g);const table=document.querySelector<HTMLElement>('.stud-game')!;expect(document.activeElement).toBe(table);fireEvent.keyDown(table,{key:'c'});expect(stored().revision).toBe(g.revision+1);
  cleanup();localStorage.clear();resume(g);fireEvent.click(screen.getByRole('button',{name:'封顶'}));const raise=screen.getByRole('button',{name:/有效全下至/});raise.focus();fireEvent.click(raise);fireEvent.click(screen.getByRole('button',{name:'确认有效全下'}));expect(screen.queryByRole('dialog')).toBeNull();expect(document.activeElement).toBe(document.querySelector('.stud-game'));
 });
 it('resumed AI waits and advances once, while visibility blocks timers',()=>{let g=startHand(initial(),()=>.4);if(g.turn===0)g=act(g,0,{type:'check'});expect(g.turn).toBe(1);saveGame(g);render(<StudGame/>);reactAct(()=>vi.advanceTimersByTime(5000));expect(stored()).toEqual(g);fireEvent.click(screen.getByRole('button',{name:/继续对局/}));Object.defineProperty(document,'hidden',{configurable:true,value:true});fireEvent(document,new Event('visibilitychange'));reactAct(()=>vi.advanceTimersByTime(5000));expect(stored()).toEqual(g);Object.defineProperty(document,'hidden',{configurable:true,value:false});fireEvent(document,new Event('visibilitychange'));reactAct(()=>vi.advanceTimersByTime(850));expect(stored().revision).toBe(g.revision+1)});
 it('resumed dealing and runout keep their original deck and next cards',()=>{let g=humanGame();g=act(g,0,{type:'check'});if(g.phase==='betting')g=act(g,1,{type:'check'});expect(g.phase).toBe('dealing');resume(g);reactAct(()=>vi.advanceTimersByTime(650));expect(stored()).toEqual(advance(g,g.revision))});
 it('reports unavailable persistence and keeps the game playable',()=>{const spy=vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('quota')});render(<StudGame/>);expect(screen.getByText(/浏览器未能保存进度/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/入席/}));expect(screen.queryByRole('button',{name:/入席/})).toBeNull();spy.mockRestore()});
 it('out-of-game focus and range input ignore keyboard actions',()=>{resume(humanGame());const g=stored();const outside=document.createElement('button');outside.textContent='宿主导航';document.body.append(outside);outside.focus();expect(document.activeElement).toBe(outside);fireEvent.keyDown(outside,{key:'f'});expect(stored()).toEqual(g);outside.remove();const slider=screen.getByRole('slider',{name:'本轮下注总额'});slider.focus();fireEvent.keyDown(slider,{key:'f'});expect(stored()).toEqual(g)});
});

 it('restored runout deals exactly one original pair without repeating a payment',()=>{const g=startHand(initial([3,997]),()=>.4);resume(g);reactAct(()=>vi.advanceTimersByTime(650));expect(stored()).toEqual(advance(g,g.revision));expect(stored().pot).toBe(6)});
 it('new match from a paused restored game resets and can start immediately',()=>{saveGame(humanGame());render(<StudGame/>);fireEvent.click(screen.getByRole('button',{name:/新对局/}));fireEvent.click(screen.getByRole('button',{name:'确认新对局'}));const start=screen.getByRole('button',{name:/入席/});expect(start.hasAttribute('disabled')).toBe(false);fireEvent.click(start);expect(stored().hand).toBe(1);expect(stored().pot).toBe(10)});
describe('round indicator and personality',()=>{
 it('shows a readable round label and marks the current step',()=>{render(<StudGame persist={false}/>);expect(screen.getByText('等待发牌')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/入席/}));const steps=screen.getByRole('list',{name:'第 1 轮，共四轮'});expect(steps.querySelector('[aria-current="step"]')?.textContent).toBe('12 张');expect(screen.getByText(/轮下注/, {selector:'strong'}).textContent).toBe('第 1 / 4 轮下注')});
 it('persists a chosen personality, shows it at the table and locks it mid-hand',()=>{const a=render(<StudGame/>);fireEvent.click(screen.getByRole('button',{name:'设置'}));const select=screen.getByRole('combobox',{name:/对手性格/}) as HTMLSelectElement;fireEvent.change(select,{target:{value:'bluffer'}});expect(localStorage.getItem('velvet-stud-v1-personality')).toBe('bluffer');fireEvent.click(screen.getByRole('button',{name:'关闭弹窗'}));expect(screen.getByText('AI · 诈唬')).toBeTruthy();a.unmount();render(<StudGame/>);expect(screen.getByText(/标准 AI · 诈唬/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/入席/}));fireEvent.click(screen.getByRole('button',{name:'设置'}));expect((screen.getByRole('combobox',{name:/对手性格/}) as HTMLSelectElement).disabled).toBe(true)});
 it('ignores an unknown stored personality',()=>{localStorage.setItem('velvet-stud-v1-personality','__proto__');render(<StudGame/>);expect(screen.getByText(/标准 AI · 均衡/)).toBeTruthy()});
 it('retains detailed AI advice when using a saved personality',()=>{
  let g=startHand(initial(),()=>.4);if(g.turn===0)g=act(g,0,{type:'check'});
  localStorage.setItem('velvet-stud-v1-personality','aggressive');resume(g);reactAct(()=>vi.advanceTimersByTime(850));
  const review=stored().reviews.at(-1)!;expect(review.seat).toBe(1);expect(review.reason).toContain('激进风格');expect(review.advice?.snapshot.own).toEqual(g.cards[1]);expect(review.advice?.alternatives.length).toBeGreaterThan(1);
 });
});

describe('clear stakes and retrospective advice',()=>{
 it('shows a raise as this-click spending and the actual resulting balance',()=>{
  let g=startHand(initial(),()=>.4);if(g.turn===0)g=act(g,0,{type:'check'});g=act(g,1,{type:'raise',to:20});resume(g);
  expect(within(screen.getByLabelText('你的筹码')).getByText('495')).toBeTruthy();expect(within(screen.getByLabelText('夜莺筹码')).getByText('475')).toBeTruthy();
  const range=screen.getByRole('slider',{name:'本轮下注总额'});expect(range.getAttribute('min')).toBe('40');expect(range.getAttribute('max')).toBe('495');
  fireEvent.change(range,{target:{value:'70'}});const preview=screen.getByLabelText('本次下注预览');expect(within(preview).getByText('70')).toBeTruthy();expect(within(preview).getByText('425')).toBeTruthy();expect(screen.getByText(/若对手跟注，底池将为 150/)).toBeTruthy();
  fireEvent.click(screen.getByRole('button',{name:/确认下注至 70/}));expect(stored().stacks[0]).toBe(425);expect(stored().paid[0]).toBe(70);expect(stored().pot).toBe(100);expect(screen.queryByLabelText('赛后复盘建议')).toBeNull();
 });
 it('explains the only legal short effective all-in instead of an impossible minimum',()=>{
  let g=startHand(initial([12,988]),()=>.4);if(g.turn===1)g=act(g,1,{type:'check'});resume(g);
  const range=screen.getByRole('slider',{name:'本轮下注总额'});expect(range.getAttribute('min')).toBe('7');expect(range.getAttribute('max')).toBe('7');expect(screen.getByText(/只能有效全下至 7/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/有效全下至 7/}));expect(screen.getByRole('dialog').textContent).toContain('本次投入 7');expect(stored().stacks[0]).toBe(7);
 });
 it('shows player advice only after settlement and keeps folded AI hole-card analysis hidden',()=>{
  let g=startHand(initial(),()=>.4);if(g.turn===0)g=act(g,0,{type:'check'});const raise={type:'raise',to:20} as const;g=act(g,1,raise,g.revision,analyzeDecision(view(g,1),raise,'normal',()=>.47));const fold={type:'fold'} as const;g=act(g,0,fold,g.revision,analyzeDecision(view(g,0),fold,'normal',()=>.47));expect(g.revealed).toBe(false);saveGame(g);render(<StudGame/>);
  expect(screen.queryByLabelText('赛后复盘建议')).toBeNull();fireEvent.click(screen.getByRole('button',{name:/查看赛后复盘建议/}));const panel=screen.getByLabelText('赛后复盘建议');expect(within(panel).getByText('建议考虑')).toBeTruthy();expect(within(panel).getByText('当时你的牌')).toBeTruthy();expect(within(panel).getByText('当时对手明牌')).toBeTruthy();expect(within(panel).getByText('下一步记住')).toBeTruthy();expect(within(panel).queryByText('当时 AI 自己的牌')).toBeNull();expect(within(panel).getByText(/对手暗牌保持隐藏/)).toBeTruthy();expect(within(panel).getAllByText('估计权益').length).toBe(1);
 });
 it('retains old settled reviews without inventing missing candidates or snapshots',()=>{
  const g=humanGame(),fold={type:'fold'} as const;const settled=act(g,0,fold,g.revision,{seat:0,street:g.street,action:'弃牌',equity:.4,odds:0,reason:'旧判断记录'});saveGame(settled);render(<StudGame/>);fireEvent.click(screen.getByRole('button',{name:/查看赛后复盘建议/}));expect(screen.getByText(/旧记录：当时仅保存行动与权益/)).toBeTruthy();expect(screen.getByText('旧判断记录')).toBeTruthy();expect(screen.queryByText('建议考虑')).toBeNull();
 });
});
