import type { SceneDefinition, WorldAction } from './types';
import { corridor } from './navigation.ts';
const rect = (x: number, y: number, w: number, h: number) => [
  [x, y],
  [x + w, y],
  [x + w, y + h],
  [x, y + h],
];
// The deck geometry follows the image's visible paved surface. Furniture remains solid.
export const ARCHIVE_GANTRY = [
  [1342, 381],
  [1200, 438],
  [1120, 417],
  [1028, 370],
  [995, 350],
];
const ring = [
  [590, 918],
  [840, 873],
  [1012, 803],
  [1150, 747],
  [1214, 661],
  [1219, 549],
  [1280, 447],
  [1350, 375],
  [1377, 302],
  [1340, 228],
  [1245, 160],
  [1108, 85],
  [1011, 47],
  [930, 44],
  [841, 94],
  [720, 69],
  [604, 119],
  [485, 200],
  [372, 255],
  [291, 329],
  [264, 412],
  [269, 463],
  [179, 523],
  [128, 606],
  [149, 702],
  [225, 789],
  [380, 886],
  [590, 918],
];
const room = (
  id: string,
  title: string,
  en: string,
  frame: number,
  returnSpawn: string,
  nodes: SceneDefinition['nodes'],
  obstacles: number[][][],
  foreground: SceneDefinition['foreground'] = [],
): SceneDefinition => ({
  id,
  title,
  en,
  description: '沿着舱内的通道，翻开这里的记录。',
  art: '/art/mecha-interiors.png',
  frame,
  width: 887,
  height: 591,
  playerScale: 0.43,
  layoutVersion: 21,
  returnTo: { sceneId: 'hub', spawnId: returnSpawn },
  overview: { x: 50, y: 50 },
  spawnPoints: { default: { x: 445, y: 467 } },
  walkable: [
    [
      [280, 228],
      [612, 228],
      [662, 298],
      [700, 362],
      [689, 429],
      [613, 481],
      [523, 494],
      [487, 550],
      [400, 550],
      [366, 494],
      [271, 481],
      [189, 431],
      [193, 340],
      [229, 293],
    ],
  ],
  obstacles,
  foreground,
  nodes: [
    {
      id: `${id}-exit`,
      x: 445,
      y: 526,
      label: '回到维修栈道',
      hint: '回到刚才的舱门外。',
      category: 'exit',
      radius: 38,
      action: { type: 'enter-scene', sceneId: 'hub', spawnId: returnSpawn },
    },
    ...nodes,
  ],
});
export const SCENES: SceneDefinition[] = [
  {
    id: 'hub',
    title: '沉睡机甲 · 维修栈道',
    en: 'THE SLEEPING ARCHIVE',
    description: '环绕完整机体的栈道，连接三个不同的舱室。',
    art: '/art/mecha-isometric.png',
    width: 1536,
    height: 1024,
    playerScale: 0.55,
    layoutVersion: 21,
    outdoor: true,
    overview: { x: 50, y: 50 },
    spawnPoints: {
      default: { x: 1065, y: 783 },
      cockpit: { x: 1162, y: 245 },
      archive: { x: 1143, y: 423 },
      workshop: { x: 1001, y: 721 },
    },
    walkable: [
      ...corridor(ring, 54),
      ...corridor(
        [
          [1272, 204],
          [1220, 232],
          [1150, 246],
          [1078, 199],
        ],
        40,
      ),
      ...corridor(ARCHIVE_GANTRY, 42),
      ...corridor(
        [
          [1039, 654],
          [1008, 687],
          [985, 744],
          [953, 810],
        ],
        43,
      ),
    ],
    nodes: [
      {
        id: 'cockpit-door',
        x: 1084,
        y: 202,
        label: '驾驶舱',
        hint: '工牌、教育经历与荣誉。',
        radius: 39,
        category: 'profile',
        action: { type: 'enter-scene', sceneId: 'life' },
      },
      {
        id: 'archive-door',
        x: 1006,
        y: 355,
        label: '胸腔档案库',
        hint: '沿检修桥进入文章与笔记的档案库。',
        radius: 36,
        category: 'blog',
        action: { type: 'enter-scene', sceneId: 'undergraduate' },
      },
      {
        id: 'workshop-door',
        x: 1037,
        y: 658,
        label: '检修工坊',
        hint: '项目，以及可以亲手接通的小回路。',
        radius: 38,
        category: 'projects',
        action: { type: 'enter-scene', sceneId: 'graduate' },
      },
      {
        id: 'hull-record',
        x: 276,
        y: 825,
        label: '机身铭牌',
        hint: '一行刻在旧装甲上的字。',
        radius: 35,
        hidden: true,
        action: {
          type: 'inspect',
          text: '「拆开，是为了理解它如何运转。」这台机甲的故事还会继续。',
        },
      },
    ],
  },
  room(
    'life',
    '驾驶舱',
    'THE COCKPIT',
    0,
    'cockpit',
    [
      {
        id: 'profile-badge',
        x: 615,
        y: 321,
        label: '驾驶员档案',
        hint: '简介、教育、经历与荣誉，收在同一份档案里。',
        category: 'profile',
        radius: 44,
        action: { type: 'open-content', contentId: 'profile' },
      },
      {
        id: 'cockpit-log',
        x: 295,
        y: 291,
        label: '航行日志',
        hint: '代码之外的生活记录。',
        category: 'blog',
        radius: 40,
        action: { type: 'open-collection', chapter: 'life' },
      },
      {
        id: 'sleeping-signal',
        x: 460,
        y: 293,
        label: '旧通讯器',
        hint: '向沉睡的机甲问一声好。',
        hidden: true,
        radius: 38,
        action: { type: 'discover', discovery: 'sleepy-eye' },
      },
    ],
    [rect(407, 220, 70, 37), rect(632, 251, 65, 68)],
    [
      {
        outline: [
          [425, 181],
          [464, 185],
          [480, 232],
          [467, 251],
          [419, 250],
          [410, 228],
        ],
        depth: 258,
      },
    ],
  ),
  room(
    'undergraduate',
    '胸腔档案库',
    'THE MEMORY CORE',
    1,
    'archive',
    [
      {
        id: 'all-articles',
        x: 445,
        y: 443,
        label: '档案终端',
        hint: '所有文章与笔记，按栏目整理。',
        category: 'blog',
        radius: 35,
        action: { type: 'open-collection' },
      },
      {
        id: 'competition-log',
        x: 590,
        y: 319,
        label: '比赛记录册',
        hint: 'ICPC 2022 合肥赛区 · SZTU_AtDawn 队总结。',
        category: 'blog',
        radius: 42,
        action: { type: 'open-content', contentId: 'cnblogs-16913984' },
      },
    ],
    [rect(372, 295, 149, 115), rect(626, 240, 76, 70)],
    [
      {
        outline: [
          [387, 239],
          [476, 242],
          [514, 254],
          [526, 377],
          [511, 414],
          [374, 414],
          [360, 375],
          [366, 267],
        ],
        depth: 414,
      },
    ],
  ),
  room(
    'graduate',
    '检修工坊',
    'THE ENGINEERING BAY',
    2,
    'workshop',
    [
      {
        id: 'project-console',
        x: 607,
        y: 347,
        label: '项目工作台',
        hint: '打开 GitHub 作品与在线演示。',
        category: 'projects',
        radius: 40,
        action: { type: 'open-projects' },
      },
      {
        id: 'circuit-console',
        x: 283,
        y: 347,
        label: '备用电路',
        hint: '转动接头，让电流走到出口。',
        category: 'play',
        radius: 40,
        action: { type: 'open-game', game: 'circuit' },
      },
      {
        id: 'workshop-notes',
        x: 448,
        y: 278,
        label: '工程笔记',
        hint: '研习、验证与协作的记录。',
        category: 'blog',
        radius: 35,
        action: { type: 'open-collection', chapter: 'graduate' },
      },
    ],
    [rect(390, 215, 110, 32), rect(625, 267, 70, 62), rect(188, 273, 72, 58)],
  ),
];
export const getScene = (id: string) =>
  SCENES.find((s) => s.id === id) ?? SCENES[0];
export const CHAPTERS = [
  {
    id: 'undergraduate',
    title: '本科',
    subtitle: '2019–2023',
    scene: 'undergraduate',
  },
  { id: 'graduate', title: '研究生', subtitle: '2025 至今', scene: 'graduate' },
  { id: 'life', title: '杂谈', subtitle: '沿途拾录', scene: 'life' },
] as const;
export const DISTRICTS: {
  id: string;
  title: string;
  subtitle: string;
  nodeId: string;
  action: WorldAction;
  sceneId: string;
  position: { x: number; y: number };
}[] = [
  {
    id: 'profile',
    title: '驾驶舱',
    subtitle: '简介、教育、经历与荣誉',
    nodeId: 'cockpit-door',
    sceneId: 'life',
    action: { type: 'open-content', contentId: 'profile' },
    position: { x: 70, y: 19 },
  },
  {
    id: 'blog',
    title: '胸腔档案库',
    subtitle: '全部文章与笔记',
    nodeId: 'archive-door',
    sceneId: 'undergraduate',
    action: { type: 'open-collection' },
    position: { x: 64.8, y: 34 },
  },
  {
    id: 'projects',
    title: '检修工坊',
    subtitle: 'GitHub 作品与在线演示',
    nodeId: 'workshop-door',
    sceneId: 'graduate',
    action: { type: 'open-projects' },
    position: { x: 68.3, y: 64 },
  },
];
