import type { SceneDefinition, WorldAction } from './types';
import { corridor } from './navigation.ts';
const rect = (x: number, y: number, w: number, h: number) => [
  [x, y],
  [x + w, y],
  [x + w, y + h],
  [x, y + h],
];
// The deck geometry follows the image's visible paved surface. Furniture remains solid.
export const ARCHIVE_GANTRY = [
  [1342, 381],
  [1200, 438],
  [1120, 417],
  [1028, 370],
  [995, 350],
];
const ring = [
  [590, 918],
  [840, 873],
  [1012, 803],
  [1150, 747],
  [1214, 661],
  [1219, 549],
  [1280, 447],
  [1350, 375],
  [1377, 302],
  [1340, 228],
  [1245, 160],
  [1108, 85],
  [1011, 47],
  [930, 44],
  [841, 94],
  [720, 69],
  [604, 119],
  [485, 200],
  [372, 255],
  [291, 329],
  [264, 412],
  [269, 463],
  [179, 523],
  [128, 606],
  [149, 702],
  [225, 789],
  [380, 886],
  [590, 918],
];
const room = (
  id: string,
  title: string,
  en: string,
  frame: number,
  returnSpawn: string,
  nodes: SceneDefinition['nodes'],
  obstacles: number[][][],
  foreground: SceneDefinition['foreground'] = [],
): SceneDefinition => ({
  id,
  title,
  en,
  description: '沿着舱内的通道，翻开这里的记录。',
  art: [
    '/art/interior-cockpit-hd.png',
    '/art/interior-library-hd.png',
    '/art/interior-workshop-hd.png',
  ][frame],
  width: 887,
  height: 591,
  playerScale: 0.43,
  layoutVersion: 22,
  returnTo: { sceneId: 'hub', spawnId: returnSpawn },
  overview: { x: 50, y: 50 },
  spawnPoints: {
    default: { x: frame === 0 ? 444 : 435, y: frame === 1 ? 449 : 443 },
    ...(id === 'undergraduate' ? { 'private-door': { x: 280, y: 345 } } : {}),
  },
  walkable: [
    [
      [276, 228],
      [612, 228],
      [662, 298],
      [700, 362],
      [689, 429],
      [613, 481],
      [523, 494],
      [487, 550],
      [400, 550],
      [366, 494],
      [271, 481],
      [189, 431],
      [193, 340],
      [220, 289],
    ],
  ],
  obstacles,
  foreground,
  nodes: [
    {
      id: `${id}-exit`,
      x: frame === 0 ? 444 : frame === 1 ? 428 : 435,
      y: frame === 1 ? 533 : 526,
      label: '回到环行栈道',
      hint: '回到刚才的舱门外。',
      category: 'exit',
      radius: 38,
      action: { type: 'enter-scene', sceneId: 'hub', spawnId: returnSpawn },
    },
    ...nodes,
  ],
});
export const SCENES: SceneDefinition[] = [
  {
    id: 'hub',
    title: '沉睡机甲 · 环行栈道',
    en: 'THE SLEEPING ARCHIVE',
    description: '环绕完整机体的栈道，连接三个不同的舱室。',
    art: '/art/mecha-isometric.png',
    width: 1536,
    height: 1024,
    playerScale: 0.55,
    layoutVersion: 22,
    outdoor: true,
    overview: { x: 50, y: 50 },
    spawnPoints: {
      default: { x: 1065, y: 783 },
      cockpit: { x: 1162, y: 245 },
      archive: { x: 1143, y: 423 },
      workshop: { x: 1001, y: 721 },
    },
    walkable: [
      ...corridor(ring, 54),
      ...corridor(
        [
          [1272, 204],
          [1220, 232],
          [1150, 246],
          [1078, 199],
        ],
        40,
      ),
      ...corridor(ARCHIVE_GANTRY, 42),
      ...corridor(
        [
          [1039, 654],
          [1008, 687],
          [985, 744],
          [953, 810],
        ],
        43,
      ),
    ],
    nodes: [
      {
        id: 'cockpit-door',
        x: 1084,
        y: 202,
        label: '航迹室',
        hint: '工牌、教育经历与荣誉。',
        radius: 39,
        category: 'profile',
        action: { type: 'enter-scene', sceneId: 'life' },
      },
      {
        id: 'archive-door',
        x: 1006,
        y: 355,
        label: '旧纸库',
        hint: '沿检修桥进入文章与笔记的档案库。',
        radius: 36,
        category: 'blog',
        action: { type: 'enter-scene', sceneId: 'undergraduate' },
      },
      {
        id: 'workshop-door',
        x: 1037,
        y: 658,
        label: '试作间',
        hint: '项目，以及可以亲手接通的小回路。',
        radius: 38,
        category: 'projects',
        action: { type: 'enter-scene', sceneId: 'graduate' },
      },
      {
        id: 'hull-record',
        x: 276,
        y: 825,
        label: '机身铭牌',
        hint: '一行刻在旧装甲上的字。',
        radius: 35,
        hidden: true,
        action: {
          type: 'inspect',
          text: '「拆开，是为了理解它如何运转。」这台机甲的故事还会继续。',
        },
      },
    ],
  },
  room(
    'life',
    '航迹室',
    'THE WAYFINDER',
    0,
    'cockpit',
    [
      {
        id: 'profile-badge',
        x: 615,
        y: 321,
        label: '驾驶员档案',
        hint: '简介、教育、经历与荣誉，收在同一份档案里。',
        category: 'profile',
        radius: 44,
        action: { type: 'open-content', contentId: 'profile' },
      },
      {
        id: 'cockpit-log',
        x: 295,
        y: 291,
        label: '航行日志',
        hint: '代码之外的生活记录。',
        category: 'blog',
        radius: 40,
        action: { type: 'open-collection', chapter: 'life' },
      },
      {
        id: 'sleeping-signal',
        x: 234,
        y: 337,
        effectPoint: { x: 155, y: 230 },
        label: '旧电台',
        hint: '旋钮旁还亮着一粒小灯。',
        hidden: true,
        radius: 38,
        action: { type: 'discover', discovery: 'sleepy-eye' },
      },
    ],
    [rect(411, 214, 66, 37), rect(658, 254, 47, 48)],
    [
      {
        outline: [
          [418, 166],
          [462, 164],
          [474, 189],
          [472, 230],
          [459, 247],
          [417, 246],
          [407, 230],
          [409, 190],
        ],
        depth: 251,
      },
    ],
  ),
  room(
    'undergraduate',
    '旧纸库',
    'THE PAPER ARCHIVE',
    1,
    'archive',
    [
      {
        id: 'all-articles',
        x: 428,
        y: 416,
        label: '阅览桌',
        hint: '所有文章与笔记，按栏目整理。',
        category: 'blog',
        radius: 35,
        action: { type: 'open-collection' },
      },
      {
        id: 'competition-log',
        x: 590,
        y: 319,
        label: '比赛记录册',
        hint: 'ICPC 2022 合肥赛区 · SZTU_AtDawn 队总结。',
        category: 'blog',
        radius: 42,
        action: { type: 'open-content', contentId: 'cnblogs-16913984' },
      },
      {
        id: 'private-door',
        x: 280,
        y: 315,
        effectPoint: { x: 220, y: 220 },
        label: '书柜后的一扇窄门',
        hint: '锁孔里透出一点暖光。',
        hidden: true,
        radius: 32,
        action: { type: 'open-vault' },
      },
      {
        id: 'folded-page',
        x: 645,
        y: 324,
        effectPoint: { x: 726, y: 236 },
        label: '书页上的纸鹤',
        hint: '有人把这一页折了起来。',
        hidden: true,
        radius: 30,
        action: { type: 'discover', discovery: 'paper-crane' },
      },
    ],
    [
      [
        [355, 296],
        [501, 296],
        [513, 342],
        [513, 379],
        [504, 388],
        [356, 388],
        [344, 378],
        [344, 342],
      ],
      rect(660, 253, 44, 48),
    ],
    [
      {
        outline: [
          [366, 246],
          [378, 252],
          [473, 252],
          [491, 246],
          [507, 258],
          [509, 324],
          [513, 341],
          [512, 379],
          [504, 387],
          [357, 387],
          [347, 376],
          [344, 342],
          [349, 325],
          [349, 261],
        ],
        depth: 388,
      },
    ],
  ),
  room(
    'graduate',
    '试作间',
    'THE PROTOTYPE ROOM',
    2,
    'workshop',
    [
      {
        id: 'project-console',
        x: 665,
        y: 373,
        label: '项目工作台',
        hint: '打开 GitHub 作品与在线演示。',
        category: 'projects',
        radius: 40,
        action: { type: 'open-projects' },
      },
      {
        id: 'circuit-console',
        x: 283,
        y: 347,
        label: '备用电路',
        hint: '转动接头，让电流走到出口。',
        category: 'play',
        radius: 40,
        action: { type: 'open-game', game: 'circuit' },
      },
      {
        id: 'workshop-notes',
        x: 448,
        y: 278,
        label: '工程笔记',
        hint: '研习、验证与协作的记录。',
        category: 'blog',
        radius: 35,
        action: { type: 'open-collection', chapter: 'graduate' },
      },
      {
        id: 'tiny-repairer',
        x: 608,
        y: 295,
        effectPoint: { x: 697, y: 225 },
        label: '桌角的小机甲',
        hint: '它似乎正在值班。',
        hidden: true,
        radius: 30,
        action: { type: 'discover', discovery: 'pocket-mecha' },
      },
    ],
    [rect(363, 194, 157, 35), rect(639, 267, 59, 62), rect(188, 273, 72, 58)],
  ),
  {
    id: 'vault',
    title: '私藏室',
    en: 'A ROOM OF ONE’S OWN',
    description: '有些页，只留给自己。',
    art: '/art/interior-vault-hd.png',
    width: 887,
    height: 591,
    playerScale: 0.43,
    layoutVersion: 22,
    returnTo: {
      sceneId: 'undergraduate',
      spawnId: 'private-door',
    },
    overview: {
      x: 50,
      y: 50,
    },
    spawnPoints: {
      default: {
        x: 442,
        y: 451,
      },
    },
    walkable: [
      [
        [249, 206],
        [631, 206],
        [638, 268],
        [741, 314],
        [743, 432],
        [655, 460],
        [577, 478],
        [537, 491],
        [372, 491],
        [298, 481],
        [226, 461],
        [149, 433],
        [151, 347],
        [203, 335],
        [240, 286],
      ],
      [
        [375, 471],
        [509, 471],
        [509, 565],
        [375, 565],
      ],
    ],
    obstacles: [
      [
        [77, 245],
        [240, 230],
        [241, 289],
        [207, 336],
        [154, 345],
        [75, 327],
      ],
      [
        [270, 167],
        [608, 167],
        [608, 207],
        [269, 207],
      ],
      [
        [642, 202],
        [721, 230],
        [774, 286],
        [755, 309],
        [658, 256],
      ],
      [
        [47, 328],
        [136, 328],
        [151, 447],
        [84, 447],
      ],
      [
        [751, 298],
        [830, 298],
        [832, 433],
        [763, 440],
      ],
    ],
    nodes: [
      {
        id: 'vault-exit',
        x: 442,
        y: 533,
        label: '回到旧纸库',
        hint: '回到书柜前的通道。',
        category: 'exit',
        radius: 34,
        action: {
          type: 'enter-scene',
          sceneId: 'undergraduate',
          spawnId: 'private-door',
        },
      },
      {
        id: 'vault-notebook',
        x: 255,
        y: 313,
        effectPoint: {
          x: 162,
          y: 241,
        },
        label: '旧笔记',
        hint: '翻开只属于自己的记录。',
        radius: 35,
        action: {
          type: 'open-vault',
        },
      },
      {
        id: 'vault-archive',
        x: 444,
        y: 233,
        effectPoint: {
          x: 442,
          y: 156,
        },
        label: '私人档案柜',
        hint: '把过去写下的话收好。',
        radius: 35,
        action: {
          type: 'open-vault',
        },
      },
      {
        id: 'vault-inscription',
        x: 620,
        y: 305,
        effectPoint: {
          x: 702,
          y: 211,
        },
        label: '柜门上的小字',
        hint: '一行不太显眼的字。',
        radius: 32,
        hidden: true,
        action: {
          type: 'inspect',
          text: '「这里不需要交出一个更好的自己。先坐一会儿。」',
        },
      },
    ],
  },
];
export const getScene = (id: string) =>
  SCENES.find((s) => s.id === id) ?? SCENES[0];
export const CHAPTERS = [
  {
    id: 'undergraduate',
    title: '本科',
    subtitle: '2019–2023',
    scene: 'undergraduate',
  },
  { id: 'graduate', title: '研究生', subtitle: '2025 至今', scene: 'graduate' },
  { id: 'life', title: '杂谈', subtitle: '沿途拾录', scene: 'life' },
] as const;
export const DISTRICTS: {
  id: string;
  title: string;
  subtitle: string;
  nodeId: string;
  action: WorldAction;
  sceneId: string;
  position: { x: number; y: number };
}[] = [
  {
    id: 'profile',
    title: '航迹室',
    subtitle: '简介、教育、经历与荣誉',
    nodeId: 'cockpit-door',
    sceneId: 'life',
    action: { type: 'open-content', contentId: 'profile' },
    position: { x: 70, y: 19 },
  },
  {
    id: 'blog',
    title: '旧纸库',
    subtitle: '全部文章与笔记',
    nodeId: 'archive-door',
    sceneId: 'undergraduate',
    action: { type: 'open-collection' },
    position: { x: 64.8, y: 34 },
  },
  {
    id: 'projects',
    title: '试作间',
    subtitle: 'GitHub 作品与在线演示',
    nodeId: 'workshop-door',
    sceneId: 'graduate',
    action: { type: 'open-projects' },
    position: { x: 68.3, y: 64 },
  },
];
