// @vitest-environment jsdom
import{act,cleanup,fireEvent,render,screen}from'@testing-library/react';import{afterEach,beforeEach,describe,expect,it,vi}from'vitest';import{BlackjackGame}from'./BlackjackGame';import{emptySaved}from'./storage';
vi.mock('./coachWorkerClient',()=>({createCoachWorker:()=>({worker:{postMessage(){},terminate(){}},dispose(){}})}));
vi.mock('./solver',()=>({strategicDealer:vi.fn(()=>({action:'stand',method:'exact-finite'}))}));
async function tick(ms=300){await act(async()=>{vi.advanceTimersByTime(ms);});}async function deal(){fireEvent.click(screen.getByRole('button',{name:/开始对局/}));for(let i=0;i<6;i++)await tick();}async function finish(){fireEvent.click(screen.getByRole('button',{name:/^停牌/}));for(let i=0;i<10&&!screen.queryByRole('button',{name:/再来一局/});i++)await tick(600);}
beforeEach(()=>{vi.useFakeTimers();localStorage.clear();vi.spyOn(Math,'random').mockReturnValue(.5);Object.defineProperty(document,'hidden',{configurable:true,value:false});});afterEach(()=>{cleanup();vi.useRealTimers();vi.restoreAllMocks();});
describe('two-mode component lifecycle',()=>{
 it('guards rapid contradictory keys, reveals dealer only after player stand, counts once',async()=>{const end=vi.fn();render(<BlackjackGame globalKeyboard persist={false} onRoundEnd={end}/>);await deal();expect(screen.getAllByRole('img',{name:'暗牌'}).length).toBe(1);fireEvent.keyDown(document.body,{key:'s'});fireEvent.keyDown(document.body,{key:'h'});fireEvent.keyDown(document.body,{key:'h'});for(let i=0;i<10;i++)await tick(600);expect(end).toHaveBeenCalledTimes(1);expect(screen.queryByRole('img',{name:'暗牌'})).toBeNull();});
 it('cleans pending timers on unmount',async()=>{const end=vi.fn();const v=render(<BlackjackGame onRoundEnd={end}/>);fireEvent.click(screen.getByRole('button',{name:/开始对局/}));await tick();v.unmount();await tick(20000);expect(end).not.toHaveBeenCalled();});
 it('blocks mode switch and reset during play; resets only selected mode',async()=>{const data=emptySaved();data.stats.classic.wins=3;data.stats.strategic.wins=8;localStorage.setItem('twenty-one:v2',JSON.stringify({version:2,...data}));render(<BlackjackGame/>);await deal();expect((screen.getByRole('button',{name:/策略庄家 庄家/})as HTMLButtonElement).disabled).toBe(true);expect((screen.getByRole('button',{name:'重置记录'})as HTMLButtonElement).disabled).toBe(true);await finish();fireEvent.click(screen.getByRole('button',{name:'重置记录'}));fireEvent.keyDown(window,{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'重置记录'}));fireEvent.click(screen.getByRole('button',{name:'清空记录'}));expect(screen.getByText('共 0 局')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/策略庄家 庄家/}));expect(screen.getByText('共 8 局')).toBeTruthy();});
 it('pauses in background until explicit continue',async()=>{render(<BlackjackGame/>);fireEvent.click(screen.getByRole('button',{name:/开始对局/}));Object.defineProperty(document,'hidden',{configurable:true,value:true});fireEvent(document,new Event('visibilitychange'));await tick(10000);expect(screen.getByRole('dialog')).toBeTruthy();expect(screen.queryByRole('img')).toBeNull();Object.defineProperty(document,'hidden',{configurable:true,value:false});fireEvent(document,new Event('visibilitychange'));expect(screen.getByRole('dialog')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'继续对局'}));for(let i=0;i<6;i++)await tick();expect(screen.getAllByRole('img').length).toBe(4);});
 it('starts coach off, offers review only after settlement and can turn it off',async()=>{render(<BlackjackGame/>);expect(screen.getByRole('switch',{name:'赛后教练'}).getAttribute('aria-checked')).toBe('false');fireEvent.click(screen.getByRole('switch',{name:'赛后教练'}));await deal();expect(screen.queryByRole('region',{name:'赛后教练复盘'})).toBeNull();await finish();expect(screen.getByRole('region',{name:'赛后教练复盘'})).toBeTruthy();fireEvent.click(screen.getByRole('switch',{name:'赛后教练'}));expect(screen.queryByRole('region',{name:'赛后教练复盘'})).toBeNull();});
 it('does not capture host body hotkeys by default and survives corrupt/denied storage',async()=>{localStorage.setItem('twenty-one:v2','{bad');vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error();});render(<BlackjackGame/>);expect(screen.getByText(/浏览器未允许保存/)).toBeTruthy();fireEvent.keyDown(document.body,{key:'n'});await tick(2000);expect(screen.getByRole('button',{name:/开始对局/})).toBeTruthy();});
});
