// @vitest-environment jsdom
import{act,cleanup,fireEvent,render,screen}from'@testing-library/react';import{afterEach,describe,expect,it,vi}from'vitest';import{CoachReview,type DecisionSnapshot}from'./CoachReview';import{createDeck}from'./engine';
const mock=vi.hoisted(()=>({workers:[] as Array<{onmessage:((e:unknown)=>void)|null;onerror:unknown;postMessage:ReturnType<typeof vi.fn>;terminate:ReturnType<typeof vi.fn>}>}));
vi.mock('./coachWorkerClient',()=>({createCoachWorker:()=>{const worker={onmessage:null,onerror:null,postMessage:vi.fn(),terminate:vi.fn()};mock.workers.push(worker);return{worker,dispose:worker.terminate};}}));
const deck=createDeck();const snapshots:DecisionSnapshot[]=[{action:'stand',snapshot:{playerCards:[deck[9],deck[17]],dealerUpcard:deck[28],mode:'classic',negativePeek:true}},{action:'hit',snapshot:{playerCards:[deck[2],deck[4]],dealerUpcard:deck[29],mode:'strategic',negativePeek:true}}];
afterEach(()=>{cleanup();mock.workers.length=0;});
describe('postgame worker review boundary',()=>{
 it('starts only on request; sends only historical visible info; cancels on step and unmount',()=>{const view=render(<CoachReview snapshots={snapshots} outcome="loss"/>);expect(mock.workers.length).toBe(0);fireEvent.click(screen.getByRole('button',{name:/复盘本局/}));const first=mock.workers[0];expect(first.postMessage).toHaveBeenCalledWith({id:0,snapshot:snapshots[0].snapshot});expect(Object.keys(first.postMessage.mock.calls[0][0].snapshot).sort()).toEqual(['dealerUpcard','mode','negativePeek','playerCards']);fireEvent.click(screen.getByRole('button',{name:'第 2 步'}));expect(first.terminate).toHaveBeenCalled();view.unmount();expect(mock.workers[1].terminate).toHaveBeenCalled();});
 it('rejects stale results and clearly labels approximate model and decision quality',()=>{render(<CoachReview snapshots={snapshots} outcome="loss"/>);fireEvent.click(screen.getByRole('button',{name:/复盘本局/}));const first=mock.workers[0];fireEvent.click(screen.getByRole('button',{name:'第 2 步'}));act(()=>first.onmessage?.({data:{result:{recommendation:'stand',hitEV:-1,standEV:1,bustProbability:.5,gap:2,method:'exact-finite',nodes:2}}}));expect(screen.queryByText('精确计算 · 有限单副牌')).toBeNull();act(()=>mock.workers[1].onmessage?.({data:{result:{recommendation:'hit',hitEV:.2,standEV:-.1,bustProbability:0,gap:.3,method:'replacement-model',nodes:2}}}));expect(screen.getByText('近似建议 · 独立抽牌模型')).toBeTruthy();expect(screen.getByText(/本局虽然输了/)).toBeTruthy();});
 it('same-step click keeps completed results; revisiting cache clears another step error',()=>{render(<CoachReview snapshots={snapshots} outcome="win"/>);fireEvent.click(screen.getByRole('button',{name:/复盘本局/}));act(()=>mock.workers[0].onmessage?.({data:{result:{recommendation:'stand',hitEV:-.2,standEV:.1,bustProbability:.6,gap:.3,method:'exact-finite',nodes:2}}}));fireEvent.click(screen.getByRole('button',{name:'第 1 步'}));expect(screen.getByText('精确计算 · 有限单副牌')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'第 2 步'}));act(()=>(mock.workers[1].onerror as ()=>void)());expect(screen.getByText(/浏览器无法启动复盘计算/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'第 1 步'}));expect(screen.queryByText(/浏览器无法启动复盘计算/)).toBeNull();expect(screen.getByText('精确计算 · 有限单副牌')).toBeTruthy();});
 it('reports worker failure without blocking game',()=>{render(<CoachReview snapshots={snapshots} outcome="tie"/>);fireEvent.click(screen.getByRole('button',{name:/复盘本局/}));act(()=>(mock.workers[0].onerror as ()=>void)());expect(screen.getByText(/浏览器无法启动复盘计算/)).toBeTruthy();});
});
